# coding: utf-8

"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # noqa: E501

    The version of the OpenAPI document: 0.47.0
    Contact: contact@mailinabox.email
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mailinabox_api
from mailinabox_api.api.mail_api import MailApi  # noqa: E501
from mailinabox_api.rest import ApiException


class TestMailApi(unittest.TestCase):
    """MailApi unit test stubs"""

    def setUp(self):
        self.api = mailinabox_api.api.mail_api.MailApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_add_mail_user(self):
        """Test case for add_mail_user

        Add mail user  # noqa: E501
        """
        pass

    def test_add_mail_user_privilege(self):
        """Test case for add_mail_user_privilege

        Add mail user privilege  # noqa: E501
        """
        pass

    def test_get_mail_aliases(self):
        """Test case for get_mail_aliases

        Get mail aliases  # noqa: E501
        """
        pass

    def test_get_mail_domains(self):
        """Test case for get_mail_domains

        Get mail domains  # noqa: E501
        """
        pass

    def test_get_mail_user_privileges(self):
        """Test case for get_mail_user_privileges

        Get mail user privileges  # noqa: E501
        """
        pass

    def test_get_mail_users(self):
        """Test case for get_mail_users

        Get mail users  # noqa: E501
        """
        pass

    def test_remove_mail_alias(self):
        """Test case for remove_mail_alias

        Remove mail alias  # noqa: E501
        """
        pass

    def test_remove_mail_user(self):
        """Test case for remove_mail_user

        Remove mail user  # noqa: E501
        """
        pass

    def test_remove_mail_user_privilege(self):
        """Test case for remove_mail_user_privilege

        Remove mail user privilege  # noqa: E501
        """
        pass

    def test_set_mail_user_password(self):
        """Test case for set_mail_user_password

        Set mail user password  # noqa: E501
        """
        pass

    def test_upsert_mail_alias(self):
        """Test case for upsert_mail_alias

        Upsert mail alias  # noqa: E501
        """
        pass


if __name__ == "__main__":
    unittest.main()
