# coding: utf-8

"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # noqa: E501

    The version of the OpenAPI document: 0.46.0
    Contact: contact@mailinabox.email
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mailinabox_api
from mailinabox_api.api.web_api import WebApi  # noqa: E501
from mailinabox_api.rest import ApiException


class TestWebApi(unittest.TestCase):
    """WebApi unit test stubs"""

    def setUp(self):
        self.api = mailinabox_api.api.web_api.WebApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_web_domains(self):
        """Test case for get_web_domains

        """
        pass

    def test_update_web(self):
        """Test case for update_web

        """
        pass


if __name__ == "__main__":
    unittest.main()
