# coding: utf-8

"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # noqa: E501

    The version of the OpenAPI document: 0.46.0
    Contact: contact@mailinabox.email
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import mailinabox_api
from mailinabox_api.api.system_api import SystemApi  # noqa: E501
from mailinabox_api.rest import ApiException


class TestSystemApi(unittest.TestCase):
    """SystemApi unit test stubs"""

    def setUp(self):
        self.api = mailinabox_api.api.system_api.SystemApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_system_backup_config(self):
        """Test case for get_system_backup_config

        """
        pass

    def test_get_system_backup_status(self):
        """Test case for get_system_backup_status

        """
        pass

    def test_get_system_privacy_status(self):
        """Test case for get_system_privacy_status

        """
        pass

    def test_get_system_reboot_status(self):
        """Test case for get_system_reboot_status

        """
        pass

    def test_get_system_status(self):
        """Test case for get_system_status

        """
        pass

    def test_get_system_updates(self):
        """Test case for get_system_updates

        """
        pass

    def test_get_system_upstream_version(self):
        """Test case for get_system_upstream_version

        """
        pass

    def test_get_system_version(self):
        """Test case for get_system_version

        """
        pass

    def test_reboot_system(self):
        """Test case for reboot_system

        """
        pass

    def test_update_system_backup_config(self):
        """Test case for update_system_backup_config

        """
        pass

    def test_update_system_packages(self):
        """Test case for update_system_packages

        """
        pass

    def test_update_system_privacy(self):
        """Test case for update_system_privacy

        """
        pass


if __name__ == "__main__":
    unittest.main()
