version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: pytest-randomly
    versions:
    - 3.5.0
    - 3.6.0
  - dependency-name: pytest
    versions:
    - 6.2.2
