# coding: utf-8

# flake8: noqa
"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # noqa: E501

    The version of the OpenAPI document: 0.46.0
    Contact: contact@mailinabox.email
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from mailinabox_api.models.dns_custom_record import DNSCustomRecord
from mailinabox_api.models.dns_custom_records_response import DNSCustomRecordsResponse
from mailinabox_api.models.dns_dump_domain_record import DNSDumpDomainRecord
from mailinabox_api.models.dns_dump_domain_records import DNSDumpDomainRecords
from mailinabox_api.models.dns_dump_domains import DNSDumpDomains
from mailinabox_api.models.dns_dump_response import DNSDumpResponse
from mailinabox_api.models.dns_record_type import DNSRecordType
from mailinabox_api.models.dns_secondary_nameserver_add_request import (
    DNSSecondaryNameserverAddRequest,
)
from mailinabox_api.models.dns_secondary_nameserver_response import (
    DNSSecondaryNameserverResponse,
)
from mailinabox_api.models.dns_update_request import DNSUpdateRequest
from mailinabox_api.models.dns_zones_response import DNSZonesResponse
from mailinabox_api.models.mail_alias import MailAlias
from mailinabox_api.models.mail_alias_by_domain import MailAliasByDomain
from mailinabox_api.models.mail_alias_remove_request import MailAliasRemoveRequest
from mailinabox_api.models.mail_alias_upsert_request import MailAliasUpsertRequest
from mailinabox_api.models.mail_aliases_response_format import MailAliasesResponseFormat
from mailinabox_api.models.mail_user import MailUser
from mailinabox_api.models.mail_user_add_privilege_request import (
    MailUserAddPrivilegeRequest,
)
from mailinabox_api.models.mail_user_add_request import MailUserAddRequest
from mailinabox_api.models.mail_user_by_domain import MailUserByDomain
from mailinabox_api.models.mail_user_privilege import MailUserPrivilege
from mailinabox_api.models.mail_user_remove_privilege_request import (
    MailUserRemovePrivilegeRequest,
)
from mailinabox_api.models.mail_user_remove_request import MailUserRemoveRequest
from mailinabox_api.models.mail_user_set_password_request import (
    MailUserSetPasswordRequest,
)
from mailinabox_api.models.mail_user_status import MailUserStatus
from mailinabox_api.models.mail_users_response import MailUsersResponse
from mailinabox_api.models.mail_users_response_format import MailUsersResponseFormat
from mailinabox_api.models.me_auth_status import MeAuthStatus
from mailinabox_api.models.me_response import MeResponse
from mailinabox_api.models.sslcsr_generate_request import SSLCSRGenerateRequest
from mailinabox_api.models.ssl_certificate_install_request import (
    SSLCertificateInstallRequest,
)
from mailinabox_api.models.ssl_certificates_provision_response import (
    SSLCertificatesProvisionResponse,
)
from mailinabox_api.models.ssl_certificates_provision_response_requests import (
    SSLCertificatesProvisionResponseRequests,
)
from mailinabox_api.models.ssl_status import SSLStatus
from mailinabox_api.models.ssl_status_response import SSLStatusResponse
from mailinabox_api.models.ssl_status_type import SSLStatusType
from mailinabox_api.models.status_entry import StatusEntry
from mailinabox_api.models.status_entry_extra import StatusEntryExtra
from mailinabox_api.models.status_entry_type import StatusEntryType
from mailinabox_api.models.system_backup_config_response import (
    SystemBackupConfigResponse,
)
from mailinabox_api.models.system_backup_config_update_request import (
    SystemBackupConfigUpdateRequest,
)
from mailinabox_api.models.system_backup_status import SystemBackupStatus
from mailinabox_api.models.system_backup_status_response import (
    SystemBackupStatusResponse,
)
from mailinabox_api.models.system_privacy_status import SystemPrivacyStatus
from mailinabox_api.models.system_privacy_update_request import (
    SystemPrivacyUpdateRequest,
)
from mailinabox_api.models.system_status_response import SystemStatusResponse
from mailinabox_api.models.web_domain import WebDomain
