# coding: utf-8

"""
    Mail-in-a-Box

    Mail-in-a-Box API HTTP specification.  # noqa: E501

    The version of the OpenAPI document: 0.46.0
    Contact: contact@mailinabox.email
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from mailinabox_api.configuration import Configuration


class DNSUpdateRequest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {"force": "int"}

    attribute_map = {"force": "force"}

    def __init__(self, force=None, local_vars_configuration=None):  # noqa: E501
        """DNSUpdateRequest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._force = None
        self.discriminator = None

        self.force = force

    @property
    def force(self):
        """Gets the force of this DNSUpdateRequest.  # noqa: E501

        Force an update even if mailinabox detects no changes are required.  # noqa: E501

        :return: The force of this DNSUpdateRequest.  # noqa: E501
        :rtype: int
        """
        return self._force

    @force.setter
    def force(self, force):
        """Sets the force of this DNSUpdateRequest.

        Force an update even if mailinabox detects no changes are required.  # noqa: E501

        :param force: The force of this DNSUpdateRequest.  # noqa: E501
        :type: int
        """
        if (
            self.local_vars_configuration.client_side_validation and force is None
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `force`, must not be `None`"
            )  # noqa: E501
        if (
            self.local_vars_configuration.client_side_validation
            and force is not None
            and force > 1
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `force`, must be a value less than or equal to `1`"
            )  # noqa: E501
        if (
            self.local_vars_configuration.client_side_validation
            and force is not None
            and force < 0
        ):  # noqa: E501
            raise ValueError(
                "Invalid value for `force`, must be a value greater than or equal to `0`"
            )  # noqa: E501

        self._force = force

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(
                    map(lambda x: x.to_dict() if hasattr(x, "to_dict") else x, value)
                )
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(
                    map(
                        lambda item: (item[0], item[1].to_dict())
                        if hasattr(item[1], "to_dict")
                        else item,
                        value.items(),
                    )
                )
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DNSUpdateRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, DNSUpdateRequest):
            return True

        return self.to_dict() != other.to_dict()
